services:
  db:
    image: postgres:15
    container_name: mygarage_db
    restarte: unless-stopped
    environment:
      POSTGRES_DB:${POSTGRES_DB}
      POSTGRES-USER:${POSTGRES_USER}
      POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - mygarage_data:/var/lib/postgresql/mygarage_data

volumes:
  mygarage_data:
